name: "AM" Application Manager
collections:
  categories:
    output: true
description: An "AUR-inspired" Database of AppImage packages and a CLI to manage/install/update them system-wide!
avatar: favicon.ico

google_analytics: 
piwik_analytics:
url: https://am.osowoso.org

exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  
markdown: GFM
github:
  private: false
  repository_url: "https://github.com/ivan-hc/AM"
