# Theme supports custom buttons
buttons:
  - text: "AM" Application Manager
    href: https://am.osowoso.org
    
# remote theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# web title
title: AM

# web desription
description: An "AUR-inspired" Database of AppImage packages and a CLI to manage/install/update them system-wide!

# Header buttons for downloads from github repo
show_downloads: true

# Header buttons link to github repo 
show_github: true

# Header buttons for google analytics 
#google_analytics:

# web PNG favicon
favicon: logo.svg

# Icon shown in header. From Fontawesome https://fontawesome.com/icons?m=free
#icon: fas fa-pencil-alt

# Colour gradient for the header
#header-colours: 
#  right: "#8a108c"
#  left: "#cc580c"
