title: AM Application Manager

# Cant use " in description or over 80 lines...
description: AM Application Manager - Manage 1900+ standalone apps for GNU/Linux

# This will show direct buttons for downloads zip tar.gz etc...
show_downloads: false

# This will show you link to github repo page
# show_github: true

# Never really messed with so ga don't know...
google_analytics:

# remote themes used (could be any)
remote_theme: oSoWoSo/cayman-vb-dark

# Your web PNG or svg favicon (Small icon for site in browser tab)
# favicon: logo.svg
# Create/pick your own or choose one from awesome fonts
# Icon shown in header. From Fontawesome https://fontawesome.com/icons?m=free
icon: fas fa-pencil-alt

# Colour gradient for the header - Here we can play if we want gradient color in header
# I don't like it so was off. Up to you...
# header-colours:
#  right: "#8a108c"
#  left: "#cc580c"

# This was meant for going to osowoso.org don't needed here if you don't point to osowoso main domain...
# buttons: [true]
#  - text: oSoWoSo
#    href: https://osowoso.org
