name: "auto-T"

on:
  push:
    branches: main
    paths:
      - 'programs/x86_64-apps/**'
      - 'programs/i686-apps/**'
      - 'programs/aarch64-apps/**'

  repository_dispatch:
    types: [auto]

  workflow_dispatch:

jobs:
  check-variables:
    name: "trigger 250 dispatch"
    runs-on: ubuntu-22.04
    steps:
      - name: "trigger 250 dispatch"
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/amcheck
          token: ${{ secrets.TOKEN }}
          event-type: check

      - name: "Set name"
        id: check
        run: |
          RUN_NAME="trigger 250 dispatch"
          echo "RUN_NAME=$RUN_NAME" >> $GITHUB_ENV

  lister-sync:
    name: "trigger Lister dispatch"
    runs-on: ubuntu-22.04
    steps:
      - name: "trigger Lister dispatch"
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/amcheck
          token: ${{ secrets.TOKEN }}
          event-type: sync

      - name: "Set name"
        id: lister
        run: |
          RUN_NAME="trigger Lister dispatch"
          echo "RUN_NAME=$RUN_NAME" >> $GITHUB_ENV

  test-apps:
    name: "trigger 💯 dispatch"
    runs-on: ubuntu-22.04
    steps:
      - name: "trigger 💯 dispatch"
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/amcheck
          token: ${{ secrets.TOKEN }}
          event-type: apps

      - name: "Set name"
        id: apps
        run: |
          RUN_NAME="trigger 💯 dispatch"
          echo "RUN_NAME=$RUN_NAME" >> $GITHUB_ENV

  main-clean:
    name: "trigger Clean dispatch"
    runs-on: ubuntu-22.04
    steps:
      - name: "trigger Clean dispatch"
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository_owner }}/amcheck
          token: ${{ secrets.TOKEN }}
          event-type: clean

      - name: "Set name"
        id: clean
        run: |
          RUN_NAME="trigger Clean dispatch"
          echo "RUN_NAME=$RUN_NAME" >> $GITHUB_ENV

  rename:
    runs-on: ubuntu-22.04
    steps:
      - name: "Rename"
        run: |
          echo "${{ env.RUN_NAME }}"
          echo "#TODO"
          #curl -X PATCH -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          #-H "Accept: application/vnd.github.v3+json" \
          #https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
          #-d "{\"name\": \"running: ${{ env.RUN_NAME }}\"}"
