name: "AM test suite 🧪"

env:
  TERM: xterm

on:
  push:
    branches: '**'
    paths:
      - 'modules/**'
      - INSTALL
      - APP-MANAGER
      - '!programs/**'
  pull_request:
    branches: '**'
    paths:
      - 'modules/**'
      - INSTALL
      - APP-MANAGER
      - '!programs/**'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate matrix
        id: set-matrix
        run: |
          chmod +x .github/workflows/generate-matrix.sh
          .github/workflows/generate-matrix.sh
        shell: bash

  tests:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          ls -al .github/workflows
          printf '\tSetting up environment...\n'
          printf '\n\tCreating directory structure...\n'
          mkdir -p results /usr/local/bin
          # printf '\n\tUpgrading ubuntu host...\n'
          # sudo apt update && sudo apt upgrade
          printf '\n\tInstalling dependencies...\n'
          sudo apt install -y wget curl zsync 2> /dev/null
          printf '\n\tMaking needed files executable...\n'
          chmod +x ./INSTALL
          printf '\n\tInstalling AM...\n'
          sudo ./INSTALL
          printf '\n'
          echo "Installed version: $(am version)"

      - name: Install ${{ matrix.app }}
        run: |
          am install ${{ matrix.app }}

#      - name: Test ${{ matrix.app }} installation
#        run: |
#          ./am run ${{ matrix.app }}

      - name: Uninstall ${{ matrix.app }}
        run: |
          am remove ${{ matrix.app }}
