name: "AM test suite 🧪"

env:
  TERM: xterm

on:
  push:
    branches: '**'
    paths:
      - 'modules/**'
      - INSTALL
      - APP-MANAGER
      - '!programs/**'
  pull_request:
    branches: '**'
    paths:
      - 'modules/**'
      - INSTALL
      - APP-MANAGER
      - '!programs/**'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  am:
    name: Install AM 📝
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install AM
        run: |
          ls -al .github/workflows
          printf '\tSetting up environment...\n'
          printf '\n\tCreating directory structure...\n'
          mkdir -p results /usr/local/bin
          # printf '\n\tUpgrading ubuntu host...\n'
          # sudo apt update && sudo apt upgrade
          printf '\n\tInstalling dependencies...\n'
          sudo apt install -y wget curl zsync 2> /dev/null
          printf '\n\tMaking needed files executable...\n'
          chmod +x ./INSTALL .github/workflows/test.sh
          printf '\n\tInstalling AM...\n'
          sudo ./INSTALL
          printf '\n'
          echo "Installed version: $(am version)"
          printf '\n\tRunning test 1\n' && .github/workflows/test.sh && printf '\n\tTest 1 finished\n'
          printf '\n\tRunning test 2\n' && .github/workflows/test.sh && printf '\n\tTest 2 finished\n'
          printf '\n\tRunning test 3\n' && .github/workflows/test.sh && printf '\n\tTest 3 finished\n'
          printf '\n\tRunning test 4\n' && .github/workflows/test.sh && printf '\n\tTest 4 finished\n'
          printf '\n\tRunning test 5\n' && .github/workflows/test.sh && printf '\n\tTest 5 finished\n'
          printf '\n\tRunning test 6\n' && .github/workflows/test.sh && printf '\n\tTest 6 finished\n'
