name: "🦉 translations"

on:
  push:
    paths:
      - translations/**
      - modules/**
      - APP-MANAGER
      # Trigger if action file change !! DEBUG important
      - .github/workflows/translations.yml

  workflow_dispatch:

permissions:
  packages: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: "Releasing: translations_v0.${{ github.run_number }}" # [${{ github.sha }}]"

jobs:
  sync-files:
    name: "🦉 translations"
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: "Checkout source repository"
        uses: actions/checkout@v4

      - name: "Cache dependencies"
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: wget curl torsocks zsync gettext tree
          version: 1.0

      - name: AM
        run: |
          sudo systemctl enable tor.service || systemctl enable tor.service
          sudo systemctl restart tor.service && wait || systemctl restart tor.service && wait
          chmod +x ./INSTALL
          sudo ./INSTALL 2> /dev/null || ./INSTALL

      # For now until translations are merged to AM
      # We need to overwrite installed am
      # And include translation files
      #TODO: REMOVE THIS STEP IF MERGING UPSTREAM!
      - name: "Remove this if merged"
        run: |
          cd /tmp/
          # Clone repo with localization
          git clone https://github.com/oSoWoSo/AM am-translations
          cd am-translations
          # Copy source and translated files
          cp -r translations /opt/am/
          # Copy translated modules
          cp -r modules /opt/am/
          # Copy am
          cp APP-MANAGER /opt/am/
          # Just for sure
          chmod a+x /opt/am/APP-MANAGER

      - name: Regenerate translations
        run: |
          am --translate
          rm -f /opt/am/translations/*.po~
          cp -r /opt/am/translations $GITHUB_WORKSPACE/
          echo '----------------------------------------------------------------------------'
          git status
          echo '----------------------------------------------------------------------------'
          git add translations/*
          git add translations/LINGUAS translations/*.po translations/*.pot
          git add translations/usr/share/locale/*/
          echo '----------------------------------------------------------------------------'
          tree -d
          echo '----------------------------------------------------------------------------'

      - name: Create translations branch
        uses: remarkablemark/gitploy-action@v1
        with:
          directory: translations
          branch: translations

      - name: Matrix
        id: matrix
        run: |
          FILES=$(cat translations/LINGUAS)
          MATRIX="{\"include\": ["
          for file in $FILES; do
            MATRIX+="{\"file\": \"$file\"},"
          done
          MATRIX="${MATRIX%,}]}"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-22.04
    needs: sync-files
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.sync-files.outputs.matrix) }}
    steps:
      - name: "Checkout source repository"
        uses: actions/checkout@v4

      - name: Create ${{ matrix.file }} release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: translations/usr/share/locale/${{ matrix.file }}/LC_MESSAGES/am.mo
          tag: "${{ matrix.file }}-LANG-0.${{ github.run_number }}"
          overwrite: true
          file_glob: true
          body: |
            AM ${{ matrix.file }} translation 0.${{ github.run_number }}
            am.po needs to be copied to /usr/share/locale/${{ matrix.file }}/LC_MESSAGES/
            or $HOME/.local/share/locale/${{ matrix.file }}/LC_MESSAGES/

#      - name: Create ${{ matrix.file }} release
#        uses: elgohr/Github-Release-Action@v5
#        with:
#          tag: "${{ matrix.file }}-LANG-0.${{ github.run_number }}"
#          title: "${{ matrix.file }}-LANG-0.${{ github.run_number }}"
#          workdir: translations/usr/share/locale/${{ matrix.file }}/LC_MESSAGES
#          prerelease: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Finish
        if: success()
        run: echo "${{ matrix.file }}-LANG-0.${{ github.run_number }} released" >> $GITHUB_STEP_SUMMARY
